name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:

env:
  PYTHONPATH: src
  PIP_CACHE_DIR: .cache/pip

jobs:
  pre-commit:
    uses: ./.github/workflows/pre-commit.yml

  test:
    uses: ./.github/workflows/test.yml
    needs: pre-commit

  semantic-release:
    uses: ./.github/workflows/semantic-release.yml
    needs: test
    secrets: inherit
